### PR TITLE
[masterbots.ai] Fix: browse and chat content search

### PR DESCRIPTION
**Pull request by Bran18**
Preview Content Serach + guard:

### Bot

https://github.com/user-attachments/assets/cdea4153-3941-4529-802c-7b307d80df48

### Chat 

https://github.com/user-attachments/assets/e73bd37f-70a0-4603-9ae9-dec2b4154257

### Old V Bug

https://github.com/user-attachments/assets/7124e82a-a91f-4841-a02c-382ac4609afb

### Extra No Found Guard: 
Screenshot 2024-11-11 at 1 46 24 PM

## Summary by Sourcery

Bug fixing the error with the search by implement a new search feature that enables searching within thread content, enhancing the browsing experience. Improve the search input component with dynamic placeholders and responsive design, and add visual feedback for search input focus.

New Features:
- Introduce a new search functionality that allows users to search within thread content, not just titles, enhancing the browsing experience.

Enhancements:
- Improve the search input component with a dynamic placeholder and responsive design, utilizing Tailwind CSS for better user experience.
- Add a visual indication for search input focus using a gradient background and animation.

## Release Notes

- **New Features**
	- Introduced a `ThreadSearchProvider` to enhance context management for thread searches.
	- Added search functionality to the `BrowseListItem` and `BrowseList` components, improving thread visibility based on user input.
	- Updated `BrowseSearchInput` for a more intuitive search experience with improved UI and state management.
	- Implemented loading skeletons (`BrowseListSkeleton`, `ThreadItemSkeleton`, `NoResultsSkeleton`) for better user feedback during data fetching.
	- Added a `NoResults` component to inform users when no search results are found.
	- Enhanced `UserThreadPanel` to manage thread visibility based on search input and loading states.
	- Introduced `searchThreadContent` function for improved thread filtering based on search terms.

- **Bug Fixes**
	- Enhanced feedback for users with a "No results found" message in the `BrowseList` component.

- **Documentation**
	- Updated comments and documentation for clarity throughout the components.

### CODE REVIEW

**Comment by Bran18** [comment]
Note: I found this browse design in 2 browse related issues conversations, and in one of them you mentioned that I was kinda good but that the border colors applied were not similar to the ones from MB. Please let me know if you want to keep this version that is using the MB colors or the one one we currently have 🫡 

Logics issues are fixed and should work with any of the UI versions

**Comment by Bran18** [comment]
> Note: I found this browse design in 2 browse related issues conversations, and in one of them you mentioned that I was kinda good but that the border colors applied were not similar to the ones from MB. Please let me know if you want to keep this version that is using the MB colors or the one one we currently have 🫡
> 
> Logics issues are fixed and should work with any of the UI versions

Found it: https://github.com/bitcashorg/masterbots/issues/169#issuecomment-2468390354

**Comment by AndlerRL** [comment]
> > Note: I found this browse design in 2 browse related issues conversations, and in one of them you mentioned that I was kinda good but that the border colors applied were not similar to the ones from MB. Please let me know if you want to keep this version that is using the MB colors or the one one we currently have 🫡
> > Logics issues are fixed and should work with any of the UI versions
> 
> Found it: [#169 (comment)](https://github.com/bitcashorg/masterbots/issues/169#issuecomment-2468390354)

Thanks @Bran18 for taking this a look. Yes, the rainbox colour doesn't follow 100% the UI colour schema/style. As it is, the glowing shadow in the back looks good! However, I would add the active accent colour when the search bar is focused, same colour as the glowing shadow colour. With that update, I can merge it. I will be solving the branch conflict.

**Comment by Bran18** [comment]
> accent colour

Tks for fixing the conflict, I just added the accent color you mentioned

**Comment by AndlerRL** [comment]
[Brandon Development Support - November 2024, 1 of 2](https://trello.com/c/uQypMx4x/264-brandon-development-support-november-2024-1-of-2)

**Pull request merged**
