### PR TITLE
[REF]feat: wordware integration

### PR DESCRIPTION
**Pull request by Bran18**
## Summary by CodeRabbit

- **New Features**
  - Introduced a POST endpoint for running Wordware prompts.
  - Added a `ChatLayout` component for chat-related content.
  - Implemented an `IndexPage` that renders the `PromptRunner` component.
  - Added a "Wordware" link to the header navigation.
  - Introduced various form handling components for better form management.
  - Added customizable toast notifications with multiple components.
  - Created the `Toaster` component for displaying toast messages.
  - Introduced the `PromptDescription` and `PromptRunner` components for handling prompts.
  - Established chat model configuration through the `WordwareProvider` interface.

- **Updates**
  - Updated several dependencies and added new ones for improved functionality.
  - Removed `lottie-react` from dependencies.

### CODE REVIEW

**Comment by Bran18** [comment]
# DO NOT MERGE THIS BRANCH ---- DOCUMENTATION ONLY

**Comment by AndlerRL** [comment]
@Bran18 -- I turned this PR into a Draft :eyes: to enhance the tag as docs & wip implementation

**Comment by AndlerRL** [comment]
@Bran18 -- now that we have the WW API up in develop, please confirm if this safe to close?

**Comment by Bran18** [comment]
> @Bran18 -- now that we have the WW API up in develop, please confirm if this safe to close?

100% you can close it :raised_hands: 

Note: Im still having a local backup just in case

**Pull request closed without merging**
