### PR TITLE
[masterbots.ai] fix: multi AI models guard

### PR DESCRIPTION
**Pull request by Bran18**
Open Pull Request Review
Reviewer: @AndlerRL
Requested by: @Bran18
Task Owner: @Bran18

### Description:

This PR is about adding a couple of guard to check if the env is created before initialization. And about testing the error reported by @AnoukRImola with the payload from the Anthropic model.

Testing and final result preview 

https://drive.google.com/file/d/15STlWulFz8LCSRiKP4tOWeWtoXNnPyVf/view?usp=sharing

Images:

Note: POST http://localhost:3000/api/chat 500 Internal Server Error shows everytime the model API key isn't set (.env)

Captura de pantalla 2024-06-26 a la(s) 1 30 42 p  m
Captura de pantalla 2024-06-26 a la(s) 1 30 57 p  m

## Summary by CodeRabbit

- **New Features**
	- Enhanced error handling with environment variable checks for API initializations.
- **Style**
	- Improved class naming consistency and readability across various components.
- **Bug Fixes**
	- Corrected SVG attribute names for better compatibility and rendering.

### CODE REVIEW

**Review by AndlerRL — APPROVED** [review]
LGTM! Merging for tests :+1:

> I will be tracking this PR into a ticket. Thanks!

**Comment by AndlerRL** [comment]
@Bran18 — the guards seem checking welll however, when we test, this happens:

# BlankBot

image

## Server Log Error (Vercel)

Screenshot 2024-06-26 at 16 10 37

# Chatbots (Healthbot)
image

## Server Log Error (Vercel)

image

I think on the Anthropic side we are getting these errors because we are adding a `system` instructions, which can be ignored for the `BlankBot`. For the other bots I have the same issue, but on this case we have to concatenate the content for the `system` instructions. Only there it would be able to not throw these errors. On the Llama3 side, we have to check why it is failing (requests and messages sequence), it looks that we are sending the sequence wrong, but also the error message doesn't tell much.

**Comment by Bran18** [comment]
I am quite curious about the Anthropic error @AndlerRL. It doesn't show that kind of error on the local test runs. And these ones weren't even from the BlankBot, they were from the lawBot

Captura de pantalla 2024-06-26 a la(s) 9 46 11 a  m


Captura de pantalla 2024-06-26 a la(s) 4 24 14 p  m

About Llama3, it was failing at the beginning due to a mismatch in the env names, not quite sure if there's another mismatch causing the authentication error.  Going to take a look

**Comment by Bran18** [comment]
Hey guys I did an investigation about the issue reported while trying to use the llama3 models, here is the breakdown: 

The issue is generated due to two main reasons: 

1. In our `actions.tsx` we are using the initializePerplexity with the `PERPLEXITY_API_KEY` but at Vercel we have a `LLAMA_API_KEY`. 
2. The `initializePerplexity` strategy only works with an API from https://docs.perplexity.ai/docs/getting-started (Api starts with `pplx`)

Note: More info about supported and legacy providers from the Vercel AI SDK here: https://sdk.vercel.ai/providers/ai-sdk-providers

Im making the changes and requesting the creation of a new env variable at vercel for the PERPLEXITY_API_KEY in another PR from this same branch.

**Pull request merged**
