### PR TITLE
fix: fix css details on ThreadDoubleAccordion

### LINKED ISSUE #143: Fix css details on ThreadDoubleAccordion
Image

see https://dev.masterbots.ai

### PR DESCRIPTION
**Pull request by TopETH**
Close #143 

## Summary by CodeRabbit

- **Style Updates**
	- Enhanced styling for accordion components, including adjusted margins, paddings, and borders for a cleaner, more intuitive interface.
	- Removed specific hover effects and padding styles to streamline user interactions.
	- Added new CSS classes and adjusted existing styles in various components to improve the visual presentation.

### CODE REVIEW

**Comment by AndlerRL** [comment]
@TopETH -- there are new conflicts after merging PR #205

**Comment by TopETH** [comment]
> @TopETH -- there are new conflicts after merging PR #205

Fixed the conflict. Please review it again. 🙂

**Comment by AndlerRL** [comment]
While navigating to the user view, I noticed this:

image

It is not related to the issue that is solving this PR but we have to follow this up.

**Review by AndlerRL — APPROVED** [review]
LGTM! Merging changes.

**Comment by AndlerRL** [comment]
[Review and Fix Alpha UI/UX Regressions](https://trello.com/c/9tuJtZmO/142-review-and-fix-alpha-ui-ux-regressions)

**Pull request merged**
